### ISSUE TITLE
eslint-config-recommended v3 documentation incorrect

### ISSUE THREAD

**Issue by shannonmoeller** [kunalgolani/eslint-config#9]
When upgrading from v2 to v3, the instructions in the README are no longer valid. Running `npm install eslint-config-recommended` now installs the `packages/` directory so using `recommended/node` no longer works.

![image](https://user-images.githubusercontent.com/155164/41299377-8597dc42-6e20-11e8-961a-afe1d8359e99.png)

![image](https://user-images.githubusercontent.com/155164/41299394-91fe3904-6e20-11e8-80d0-05d87ea2df8c.png)

**Comment by kunalgolani** [comment]
Hi Shannon

Thanks for reporting this. The directory change is intentional, and that's
why the major version upgrade. I'm sorry that I forgot to update the docs
to reflect the directory change.

Unfortunately, I'm traveling this week and won't be able to fix this
myself. Feel free to raise a pull request and I will merge it as soon as
I'm back.

You could also add, for example, a file in the root directory called
`esnext.js` and export `./packages/esnext` from it if you want backward
compatibility. It's less work to just update the docs though. :)

Cheers!

**Comment by shannonmoeller** [comment]
No worries! Happy to submit a PR.

What do you think about adding a `packages/eslint-config-recommended` package that imports and exports the other three? That would support the new lerna setup, restore compatibility with the old api, and keep the top level of your repo nice and clean.

**Comment by kunalgolani** [comment]
Sounds awesome!
